# Generated by Django 2.2.6 on 2021-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20211111_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(max_length=150, related_name='recipes', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
