# Generated by Django 2.2.6 on 2021-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20211114_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsquanity',
            old_name='quanity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
